

#FROM python:3.9-slim
FROM python:3.12.4-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y openjdk-17-jdk-headless curl procps && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN tar xzvf spark.tgz && mv spark-3.5.0-bin-hadoop3/ /opt/spark && rm spark.tgz

# ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-arm64
ENV SPARK_HOME /opt/spark
ENV PATH $SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH
RUN export PYTHONPATH=$(ZIPS="$SPARK_HOME"/python/lib/*.zip; IFS=:; echo "${ZIPS[*]}"):$PYTHONPATH


EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
